In [2]:
import torch 
import torch_geometric
from torch_geometric.data import Data

In [3]:
import matplotlib.pyplot as plt
import matplotlib_inline

In [11]:
# Basic dataset with three points,three edges and one face.
points_coordinates = torch.tensor([[0.5, 0.0], [-0.5, 0.0], [0.5, 0.5]])
edge_index=torch.tensor([[0, 1, 2], [1, 2, 0]], dtype=torch.long)
face_index=torch.tensor([[0], [1], [2]], dtype=torch.long)

In [14]:
# We pick a direction between 0 and 2*pi
theta = torch.tensor(0.0) 
xi = torch.tensor([torch.sin(theta),torch.cos(theta)])

In [16]:
# Next we compute the node heights as the inner product of the vertex coordinates 
# and the direction.
node_heigth = points_coordinates @ xi 
print(node_heigth)

tensor([0.0000, 0.0000, 0.5000])


In [20]:
# The "height" of each edge is defined as the maximum of the node heights of the 
# vertices it is spanned by. Since the edge indices are given as tuples, we lookup the 
# edge height tuples in the node heights vector (indexing is the same) and 
# compute the column-wise maximum. 

edge_height_tuples = node_heigth[edge_index]
edge_height = edge_height_tuples.max(dim=0)[0]
edge_height

tensor([0.0000, 0.5000, 0.5000])

In [21]:
# For the face heights we perform the same computation.
face_height_tuples = node_heigth[face_index]
face_height = face_height_tuples.max(dim=0)[0]
face_height

tensor([0.5000])

In [ ]:
# The two critical points are 0 and 1/2 and these are the places the ect changes. 
# Below zero the ecc is zero, between 0 and 1/2 it is 2-1 = 1 (2 points 1 edges)
# and above 1/2 it is  3-3+1=1. 
# We find these numbers by counting all the points edges and faces below a certain
# value. 

In [28]:
# Instead of counting points, we assign each element an indicator function that 
# zero below the critical point and 1 above it. 
# To do so, we translate the indicator function for each point, edge and face. 

# Discretize interval in 25 steps
interval = torch.linspace(-1,1,25).view(-1,1)

translated_nodes = interval - node_heigth  
ecc_points = torch.heaviside(translated_nodes,values=torch.tensor([1.0]))
print(ecc_points)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [31]:
# Note that the 0 is at index 13 and 1/2 is at index 20. Indeed this is where 
# the curves change value. 

# We do the same for the faces and edges.

In [30]:


# Discretize interval in 25 steps
interval = torch.linspace(-1,1,25).view(-1,1)

translated_edges = interval - edge_height 
ecc_edges = torch.heaviside(translated_edges,values=torch.tensor([1.0]))
print(ecc_edges)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [32]:
# Discretize interval in 25 steps
interval = torch.linspace(-1,1,25).view(-1,1)

translated_edges = interval - edge_height 
ecc_edges = torch.heaviside(translated_edges,values=torch.tensor([1.0]))
print(ecc_edges)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [33]:
# Discretize interval in 25 steps
interval = torch.linspace(-1,1,25).view(-1,1)

translated_faces = interval - face_height 
ecc_faces = torch.heaviside(translated_faces,values=torch.tensor([1.0]))
print(ecc_faces)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [37]:
# The ect along this direction is then computed by first computing the sum of
# columns in each of the three matrices and then by computing the 
# alternating sum of the three matrices.

ecc = ecc_points.sum(axis=1) - ecc_edges.sum(axis=1) + ecc_faces.sum(axis=1) 
ecc

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# We can indeed verify that at index 13 the value changes from 0 to 1 (which is)
# the origin in our coordinate system.